setxkbmap -option terminate:ctrl_alt_bksp           #Enables ctrl + alt + Bkspace
setxkbmap -option caps:escape # maps caps to escape key

~/.bin/touchEnable & 

autocutsel -fork &
autocutsel -selection PRIMARY -fork &
dunst & 
#(sleep 5 && xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55) &
(xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55) &

google-chrome-beta --no-startup-window &

while :; do xsetroot -name "`~jannua/.bin/statusbar`" ; sleep 60 ; done &
hsetroot -center ~/.icons/wallpaper.jpg &

while true; do
    dwm >> ~/.dwm.log
done
