#!/bin/bash

set -e
projectDir="`git rev-parse --show-toplevel`"

installPkgs() {
  if [ -e /etc/apt/sources.list ]; then
#    apt update
    apt install zsh clang-format clang-tidy curl -y
  else
    sudo pacman -Sy

    sudo sed -r -i 's/SigLevel.*/SigLevel = Never/g' /etc/pacman.conf
    sudo pacman -S rkt openssl git ctags tmux neovim zsh clang-tools-extra llvm llvm-libs python python-pip --noconfirm 
    sudo pip3 install --user pynvim 
  fi
}

setupNvim() {
  sudo ln -sf /usr/bin/nvim /usr/bin/vi 
  sudo ln -sf /usr/bin/nvim /usr/bin/vim 

  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  [ ! -e ~/.config/nvim ] && mkdir -p ~/.config/nvim

  ln -sf $projectDir/confs/init.vim ~/.config/nvim/init.vim
  ln -sf $projectDir/confs/tmux.conf ~/.tmux.conf
  ln -sf $projectDir/confs/zshrc ~/.zshrc
  ln -sf $projectDir/confs/shrc ~/.shrc

  nvim +PlugInstall +UpdateRemotePlugins +qall 
  sudo chsh -s /usr/bin/zsh $USER 
}

main() {
  installPkgs

  setupNvim
}

main $@
