#!/bin/bash

set -e
projectDir="`git rev-parse --show-toplevel`"

_checkUser() {
  if [ $USER = "root" ]; then
    echo "Should not run as root"
    exit 0
  fi
}

installPkgs() {
  if [ -e /etc/apt/sources.list ]; then
#    apt update
    apt install zsh clang-format clang-tidy curl -y
  else
    sudo pacman -Sy

    sudo sed -r -i 's/SigLevel.*/SigLevel = Never/g' /etc/pacman.conf
    sudo pacman -S --needed rkt openssl git ctags tmux neovim zsh clang-tools-extra llvm llvm-libs python python-pip --noconfirm 
    sudo pip3 install --user pynvim 
  fi
}

setupNvim() {
  sudo ln -sf /usr/bin/nvim /usr/bin/vi 
  sudo ln -sf /usr/bin/nvim /usr/bin/vim 

  pip3 install --user pynvim 
  pip3 install --user --upgrade pynvim

  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  [ ! -e ~/.config/nvim ] && mkdir -p ~/.config/nvim

  mkdir -p ~/.config/nvim
  mkdir -p ~/.config/dunst

  ln -sf $projectDir/bin ~/.bin
  ln -sf $projectDir/confs/init.vim ~/.config/nvim/init.vim
  ln -sf $projectDir/confs/dunstrc ~/.config/dunst/dunstrc
  ln -sf $projectDir/confs/tmux.conf ~/.tmux.conf
  ln -sf $projectDir/confs/zshrc ~/.zshrc
  ln -sf $projectDir/confs/shrc ~/.shrc
  ln -sf $projectDir/confs/xinitrc ~/.xinitrc
  ln -sf $projectDir/confs/gitconfig ~/.gitconfig
  ln -sf $projectDir/confs/git_template ~/.git_template

  mkdir -p ~/.mutt
  pushd ~/.mutt
    find ~/src/DevOps/confs/mutt -type f -exec ln -sf {} \; 
  popd

  nvim +PlugInstall +UpdateRemotePlugins +qall 

  sudo chsh -s /usr/bin/zsh $USER  || true
}

main() {
  _checkUser
  installPkgs

  setupNvim
}

main $@
