#!/bin/bash

set -e
projectDir="`git rev-parse --show-toplevel`"

installPkgs() {
  pacman -S git ctags tmux neovim zsh rkt clang-tools-extra --noconfirm 
}

setupNvim() {
  chsh -s /usr/bin/zsh $USER || true
  ln -sf /usr/bin/nvim /usr/bin/vi 
  ln -sf /usr/bin/nvim /usr/bin/vim 

  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  [ ! -e ~/.config/nvim ] && mkdir -p ~/.config/nvim

  ln -sf $projectDir/confs/init.vim ~/.config/nvim/init.vim
  ln -sf $projectDir/confs/tmux.conf ~/.tmux.conf
  ln -sf $projectDir/confs/zshrc ~/.zshrc

  nvim +PlugInstall +qall
}

main() {
  pacman -Sy

  installPkgs

  setupNvim
}

main $@
